services:
  - type: web
    name: ut-trs-backend
    rootDir: server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health
    numInstances: 1
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: ut_trs
      - key: JWT_SECRET
        sync: false
      - key: FONNTE_TOKEN
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: TIMEZONE
        value: Asia/Jakarta
      - key: WORKER
        value: "1"
  - type: static
    name: ut-trs-frontend
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
